// Code generated by hertz generator.

package main

import (
	"xzdp/biz/dal/mysql"
	"xzdp/biz/dal/redis"
	"xzdp/conf"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default(server.WithHostPorts(conf.GetConf().Hertz.Address))
	mysql.Init()
	redis.Init()

	register(h)
	h.Spin()
}
